#!/usr/bin/env bash

script/atree
script/atree_pipe1
script/atree_pipe2
script/mix_export_lv_html &&
script/mix_export_lv_json &&
script/mix_export_lv_markdown &&
script/mix_export_nested_markdown &&
script/mix_export_nested_tree &&
script/mix_list
