#!/usr/bin/env bash

cmd="./bin/atree | ./bin/atree -c stdin | ./bin/atree -c stdin"

cat << EOF >&2
---------------------------------------
COMMAND: $cmd
Demonstrate bash pipelining with two pipe elements
---------------------------------------
EOF

eval $cmd
