#!/usr/bin/env bash

cmd="./atree priv/playbooks/test2.yaml export"

cat << EOF >&2
---------------------------------------
COMMAND: $cmd
Run atree to export test2 to markdown
---------------------------------------
EOF

$cmd
