#!/usr/bin/env bash

cmd="./bin/atree | ./bin/atree -"

cat << EOF >&2
---------------------------------------
COMMAND: $cmd
Demonstrate bash pipelining with one pipe element
---------------------------------------
EOF

eval $cmd
