#!/usr/bin/env bash

cmd="mix ugen.export phx.live_view"

cat << EOF >&2
---------------------------------------
COMMAND: $cmd
Export LiveView Install Guide to Markdown
---------------------------------------
EOF

$cmd
