#!/usr/bin/env bash

cmd="mix ugen.export test.test2 --format action_tree"

cat << EOF >&2
---------------------------------------
COMMAND: $cmd
Export Nested Test to ActionTree
---------------------------------------
EOF

$cmd
