#!/usr/bin/env bash

cmd="mix ugen.export phx.live_view --format guide_json"

cat << EOF >&2
---------------------------------------
COMMAND: $cmd
Export LiveView Install Guide to JSON
---------------------------------------
EOF

$cmd
