#!/usr/bin/env bash

cmd="mix atree export test2.yaml $*"

cat << EOF >&2
---------------------------------------
 SCRIPT: $0
COMMAND: $cmd
Export Playbook
---------------------------------------
EOF

eval $cmd
