#!/usr/bin/env bash

cmd="mix atree export test.test2 --output action_tree $*"

cat << EOF >&2
---------------------------------------
COMMAND: $cmd
Export Nested Test to ActionTree
---------------------------------------
EOF

eval $cmd
