#!/usr/bin/env bash

cmd="mix atree export phx.live_view --output guide_html"

cat << EOF >&2
---------------------------------------
COMMAND: $cmd
Export LiveView Install Guide to HTML
---------------------------------------
EOF

eval $cmd
