#!/usr/bin/env bash

cmd="mix atree list $*"

cat << EOF >&2
---------------------------------------
 SCRIPT: $0
COMMAND: $cmd
List all Actions to stdout
---------------------------------------
EOF

eval $cmd
