#!/usr/bin/env bash

cmd="mix atree export util.text_block -p header='asdf' -p body='qwer' $*"

cat << EOF >&2
---------------------------------------
COMMAND: $cmd
Demonstrate use of parameters with text_block
---------------------------------------
EOF

eval $cmd
