#!/usr/bin/env bash

cmd="mix atree export | mix atree export -"

cat << EOF >&2
---------------------------------------
COMMAND: $cmd
Demonstrate bash pipelining with one pipe element
---------------------------------------
EOF

eval $cmd
