#!/usr/bin/env bash

cmd="mix atree export | mix atree export - | mix atree export - $*"

cat << EOF >&2
---------------------------------------
COMMAND: $cmd
Demonstrate bash pipelining with two pipe elements
---------------------------------------
EOF

eval $cmd
