#!/usr/bin/env bash

cmd="mix atree export $*"

cat << EOF >&2
---------------------------------------
 SCRIPT: $0
COMMAND: $cmd
Write a json context to stdout
---------------------------------------
EOF

$cmd
